server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/budget_control
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/seed

logging:
  level:
    org.hibernate.SQL: debug